# Generated by Django 5.0.6 on 2024-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioskop', '0004_movie_duration_movie_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(default='https://example.com/default-poster.jpg'),
        ),
    ]
